TRACK_WORDS = ['AngelCGM48',
               'AomCGM48',
               'ChampooCGM48',
               'FahsaiCGM48',
               'FortuneCGM48',
               'IzurinaCGM48',
               'JaydaCGM48',
               'JjaeCGM48',
               'KaiwanCGM48',
               'KaningCGM48',
               'KylaCGM48',
               'LatinCGM48',
               'MarminkCGM48',
               'MeenCGM48',
               'MeiCGM48',
               'MilkCGM48',
               'NenaCGM48',
               'NenieCGM48',
               'NichaCGM48',
               'ParimaCGM48',
               'PepoCGM48',
               'PimCGM48',
               'PingCGM48',
               'PunchCGM48',
               'SitaCGM48',
               ]
LANGUAGE = ['th']
